import React from 'react';
import { Link } from 'react-router-dom';
import { useGetMyBillsQuery } from '../../services/api';

const statusColor = { paid: 'badge-green', partial: 'badge-yellow', unpaid: 'badge-red' };

export default function MyBills() {
  const { data, isLoading } = useGetMyBillsQuery();
  const bills = data?.bills || data || [];

  const totalPending = bills.filter(b => b.status !== 'paid').reduce((s, b) => s + (b.pendingAmount || 0), 0);

  return (
    <div className="app-page">
      <div className="page-heading">
        <div>
          <h1>My Bills</h1>
          <p>Track paid, pending, and partially settled monthly bills.</p>
        </div>
        {totalPending > 0 && (
          <Link to="/payments/submit" className="btn-primary btn-sm">Pay Now ₹{totalPending}</Link>
        )}
      </div>

      {totalPending > 0 && (
        <div className="flex items-center gap-3 rounded-2xl border border-red-200 bg-red-50 px-4 py-3">
          <span className="text-xl">⚠️</span>
          <div>
            <p className="font-bold text-red-800 text-sm">Pending dues: ₹{totalPending}</p>
            <p className="text-xs text-red-600">Pay outstanding bills to continue ordering.</p>
          </div>
          <Link to="/payments/submit" className="ml-auto btn-danger btn-sm shrink-0">Pay →</Link>
        </div>
      )}

      {isLoading ? (
        <div className="card text-sm text-slate-500">Loading bills...</div>
      ) : !bills.length ? (
        <div className="empty-state">
          <div className="text-4xl mb-2">🧾</div>
          <p className="font-medium text-slate-600">No bills yet</p>
          <p className="text-xs text-slate-400 mt-1">Bills are generated by admin based on your orders.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {bills.map(b => (
            <div key={b._id} className="card">
              <div className="flex items-start justify-between gap-3">
                <div className="flex gap-3 min-w-0">
                  <div className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-xl shrink-0">🧾</div>
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="font-bold text-slate-800 text-sm">{b.billNumber}</p>
                      <span className={`badge ${statusColor[b.status] || 'badge-gray'}`}>{b.status}</span>
                    </div>
                    <p className="text-xs text-slate-500 mt-0.5">
                      {b.billingPeriodStart ? `Period: ${new Date(b.billingPeriodStart).toLocaleDateString('en-IN')}` : 'Generated bill'}
                      {b.dueDate && ` · Due: ${new Date(b.dueDate).toLocaleDateString('en-IN')}`}
                    </p>
                  </div>
                </div>
                <div className="text-right shrink-0">
                  <p className="font-bold text-slate-800">₹{b.subtotal}</p>
                  {b.pendingAmount > 0 && <p className="text-xs text-red-600 font-semibold">₹{b.pendingAmount} pending</p>}
                  {b.paidAmount > 0 && <p className="text-xs text-emerald-600">₹{b.paidAmount} paid</p>}
                </div>
              </div>
              {b.status !== 'paid' && (
                <div className="mt-3 pt-3 border-t border-slate-100">
                  <Link to="/payments/submit" className="btn-primary btn-sm">Submit Payment →</Link>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
